### ISSUE TITLE
Should format string right zero-pad (instead of left zero-pad) final bits in data before decoding?

### ISSUE THREAD

**Issue by klohner** [zuckschwerdt/bitbench#20]
I've been burned by not realizing the final hex digit of a decoding was doing this.

For example:

https://triq.net/bitbench#c=%7B5%7D02&c=%7B6%7D02&c=%7B7%7D02&c=%7B8%7D02&f=hh&cw=4

I more often expect the "hh" decoding of "{7}02" to be "02" instead of "01".

**Comment by zuckschwerdt** [comment]
At times I find that confusing too. It would be a weird special case in the code to left align though. And the output then would depend on the choosen width specifier.

I think in general formats should not try to display more bits than available.
Maybe I can insert a visual warning when not enough bits are available and the display is padded. Perhaps with an option how to pad too.

**Comment by zuckschwerdt** [comment]
Not final yet but there is a test version online now.

**Comment by klohner** [comment]
Love it!  Thank you!

I guess this is an edge case, but did you intend for the reflection of insufficient final bits to display  with "NaN"?

https://triq.net/bitbench#c=%7B5%7D02&c=%7B6%7D02&c=%7B7%7D02&c=%7B8%7D02&f=hh&z=1&r=true&cw=4

**Comment by zuckschwerdt** [comment]
That's a bug and independent. Not sure what byte-reflect for incomplete bytes means and how we could maintain the "incomplete byte" status when `{1}8` effectively turns into `{8}1`. Thoughts or ideas?

**Comment by klohner** [comment]
Perhaps it'd make as much sense to say a reflected byte of {7}02 would be 0x40 with the "incomplete byte" status?

**Comment by zuckschwerdt** [comment]
I thought that too, we'd need extra flags on the bytes then. The `0x40` by itself doesn't show that it's incomplete anymore -- it has been zero-filled by the reflection.

Alternatively we could reflect `{7}02` into `{7}80` and the user would need to uncheck the "Zero-fill" to right-align the value.

**Comment by klohner** [comment]
Hmm, it's weird because reflection is always 8 bits wide, but "h" or "d" is 4.

I seem to recall the previous behavior of reflection was to essentially pad-right to the 8-bit boundary before the reflection, and I think that already makes sense for any desired use of reflection.  And if we now show the \<incomplete\> flag to illustrate where it was zero-padded, this makes things not confusing.  Essentially, it's like the "Zero-fill \[right\]" option was already turned on in this case before.

And with this flag to represent where zeros were "added" to pad out the format string character, I'm not sure when I'd use BitBench and want an un-reflected hex value of "{3}2" to ever be "\<incomplete\>1".  But maybe that's just me.  I think "2\<incomplete\>" is what I'd always expect to see.

Here's a [BitBench](https://triq.net/bitbench#c=%7B7%7Dc2%20%5B7%20bits%2C%201100001%5D&c=%7B8%7Dc2%20%5Bif%20zero%20filled%20right%20to%204%3Dbit%20boundary%20(Zero-fill%3DON)%2C%20no%20reflection%2C%20new%20behavior%2C%20incomplete%20flag%20after%20c2%20shows%20expected%20behavior%20(IMHO)%20and%20makes%20it%20not%20confusing%5D&c=%7B8%7Dc1%20%5Bif%20zero%20filled%20left%20at%204-bit%20boundary%20(Zero-fill%3DOFF)%2C%20no%20reflection%2C%20confusing%20previous%20behavior%2C%20now%20with%20incomplete%20flag%20between%20c1%20makes%20it%20less%20confusing%2C%20but%20is%20this%20ever%20useful%3F%5D&c=%7B8%7Dc2%20%5Bif%20zero%20filled%20right%20at%208-bit%20boundary%20(Zero-fill%3DON)%2C%20then%20reflected%2C%20previous%20behavior%20I%20think%2C%20now%20with%20incomplete%20flag%20before%2043%20makes%20this%20not%20confusing%5D&c=%7B8%7D61%20%5Bif%20zero%20filled%20left%20at%208-bit%20boundary%20(Zero-fill%3DOFF)%2C%20then%20reflected%2C%20new%20behavior%2C%20incomplete%20flag%20after%2086%2C%20not%20confusing%2C%20but%20when%20would%20this%20be%20useful%20behavior%3F%5D&f=8b%0Ahh&z=1&cw=4) to illustrate my thinking.

**Comment by zuckschwerdt** [comment]
Very nice comparison in the BitBench. I agree.
note that `hh` (i.e. `4h4h`) is different from `8h` (and `d` by default is `8d`).

Problem is that a "incomplete flag" is infered by not having enough bits. After reflection with needed padding there are always enough bits and we have no info for a flag (Reflect is done very early).

I would like to indicate the truncation also after reflection, but I don't know how to get that info :/

**Comment by klohner** [comment]
Hmm.  Maybe a thought for a reimagining this implementation:

- Before decoding a row, compare its data length to all the boundaries of the decoded element list.  If "reflect" is specified, perhaps check that the format string's total length is a multiple of 8 and warn the user if not?  

  For example:
  Data: {11}ABC = length 11
  Format String: b2h3d8d = boundary lengths 0, 1, 3, 6, 14

- If the data length is between any of those boundaries, right-pad the data to the next highest length to meet a format string boundary, and somehow flag the decoded row as incomplete/zero-padded.  Maybe put the flag at the far right of the row display, or maybe just at the end of the decoding?

  For example, pad {11}ABC to {14}ABC0 and flag the decoded row.

- I can't think of when I ever have a use for left-padding a decoded element.  Is there a use case for this behavior?

- Maybe have some other flag or row highlight to denote when a format string is shorter/longer than data length, or a button to prevent the decode from looping the format string, or maybe a display for the integer difference between the format string length and the data length at the far right of the row display?  These are the kinds of things that usually trip me up when working on a decoding and I think some visual indication that there's an issue might help me.
