### ISSUE TITLE
Don't care fields

### ISSUE THREAD

**Issue by simonratner** [zuckschwerdt/bitbench#3]
Omit a field from output (e.g. padding or reserved bits).
Example: `CH:3d ?5b ID:hh` formats `60 c3` → `CH:3 ID:c3`.

**Comment by zuckschwerdt** [comment]
Not sure if a modifier or format character is needed, i.e. `CH:3d ?5b ID:hh` or `CH:3d 5x ID:hh`?
The modifier would allow quick hiding of fields and maybe a toggle switch "hide/show".
A format character would fit better (`x`, `n`, or maybe `c`onceal).
Also I like to pepper my format strings with `?` markers, maybe another character is suitable?

**Comment by simonratner** [comment]
Good call, i like the format character much better - hadn't occurred to me.

**Comment by zuckschwerdt** [comment]
I think visually `x` shows the purpose best then :)
