### ISSUE TITLE
Format bits as ASCII

### ISSUE THREAD

**Issue by hamishfagg** [zuckschwerdt/bitbench#7]
It would be great to be able to format some data as ASCII characters. That's pretty much it =)

**Comment by zuckschwerdt** [comment]
Good idea, thanks. [ASCII character output](http://triq.net/bitbench/?c=48%2045%204c%204c%204f&f=8b%20%0A....%20d%20%0A......%20c%20) went in with aa46236.

**Comment by zuckschwerdt** [comment]
Also [ctrl and 8-bit chars](http://triq.net/bitbench?c=48454c4c4f%20baa9%2000&f=8b%20%0A....%20d%20%0A......%20c%20) are visually highlighted
